services:
  app:
    image: rkooy/imgmesser-app:latest
    ports:
      - "80:80"
    environment:
      VITE_API_URL: "${VITE_API_URL}"
    volumes:
      - ./custom_nginx.conf:/etc/nginx/conf.d/custom_nginx.conf:ro
    networks:
      - imgmesser-nw

  api:
    image: rkooy/imgmesser-api:latest
    ports:
      - "8080:8080"
    environment:
      ORIGIN_ADDRESS: "${ORIGIN_ADDRESS}"
      LISTEN_ADDRESS: "${LISTEN_ADDRESS}"
      AWS_PROFILE: "${AWS_PROFILE}"
      S3_BUCKET_NAME: "${S3_BUCKET_NAME}"
      DATABASE_URL: "${DATABASE_URL}"
      MAX_CONNS: "${MAX_CONNS}"
    volumes:
      - ~/.aws:/root/.aws
    depends_on:
      - db
    networks:
      imgmesser-nw:
        ipv4_address: 172.20.0.10

  db:
    image: postgres:16-alpine
    restart: always
    environment:
      POSTGRES_USER: "${POSTGRES_USER}"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
      POSTGRES_DB: "${POSTGRES_DB}"
    volumes:
      # Persist database data to a volume on the host machine
      - postgres_data:/var/lib/postgresql/data
    networks:
      - imgmesser-nw

networks:
  imgmesser-nw:
    external: true
    name: imgmesser-nw

volumes:
  postgres_data:
